
#General settings
[general]
	#The CurseForge project ID for the modpack
	#Range: > 0
	modpackProjectID = 1012120
	#The name of the modpack
	modpackName = "Hi-Tech Revolution"
	#The version of the modpack
	modpackVersion = "0.2.2"
	#Use the metadata.json to determine the modpack version
	#ONLY ENABLE THIS IF YOU KNOW WHAT YOU ARE DOING
	useMetadata = false

