
#Range is a radius and measured in blocks.
#A value of 5 (like the torch) will cover an area of 11x11 blocks total
[Range]
	#Range (in blocks) of the Ender Torch [Default: 5]
	#Range: 1 ~ 50
	range_torch = 5
	#Range (in blocks) of the T1 Magnet [Default: 3]
	#Range: 1 ~ 32
	range_t1 = 3
	#Range (in blocks) of the T2 Magnet [Default: 6]
	#Range: 1 ~ 32
	range_t2 = 6
	#Range (in blocks) of the T3 Magnet [Default: 10]
	#Range: 1 ~ 32
	range_t3 = 10

