
[General]
	#The capacity defines how many items a full FuelCanister can smelt (default =4096 = 8 Stacks Coal)
	#Range: 0 ~ 32767
	capacity = 1024

[Fuels]
	#A List of Fuels, that will be automatically consumed when right-clicking with the FuelCanister in Hand
	#Be careful about which items you put in here, as this can have unwanted consequences! (e.g. putting wood here uses up all your wood when using a FuelCanister)
	#Format of each List Entry: Recipe-Like Json. e.g. {item: "name"} or {tag: "TagName"}
	#For a simple item without metadata, just the item-id in the form mod_id:item_id is enough
	autoFuels = ["minecraft:blaze_rod", "minecraft:coal_block", "minecraft:coal", "thermal:charcoal_block", "minecraft:charcoal", "byg:anthracite_block", "byg:anthracite", "byg:lignite_block", "byg:lignite", "thermal:sulfur_block", "thermal:sulfur", "thermal:sulfur_dust", "thermal:bitumen_block", "thermal:bitumen", "thermal:tar_block", "thermal:tar", "thermal:rosin_block", "thermal:rosin", "thermal:coal_coke_block", "thermal:coal_coke", "malum:block_of_blazing_quartz", "malum:blazing_quartz", "malum:blazing_quartz_fragment", "malum:block_of_arcane_charcoal", "malum:arcane_charcoal", "malum:arcane_charcoal_fragment", "malum:charcoal_fragment", "malum:coal_fragment", "createaddition:biomass_pellet", "kubejs:iridium_fuel_cell"]
	#If a player should be able to use any Item with a fuel value when using a crafting table to fill the FuelCanister, or only those defined by autoFuels
	craftAnyFuel = true

