
#A few general things to note:
#Any invalid entries will result in a log warning, but will just be skipped, and working entries will work.
#Most entries will utilize a block, item or enchantment id, which needs to be in the modid:blockid, modid:itemid or modid:enchantmentid format, respectively. "minecraft:" is not optional.
#All of these support regex. So you could use .* to select all entries, or minecraft:.* to select all elements in the minecraft namespace. For further information, please consult Google.
#Entries are read from left to right, this means that entries will overwrite entries read before it if they modify the same block/item/enchantment.
#NBT and blockstates are currently not supported in any way.
[logging]
	#Whether to log successful operations or not.
	log_successful = true
	#Whether to log failed operations or not.
	log_errors = true

[item_groups]
	#Define new item groups. Format is "id;icon", with icon being an item id. Will run before the below stuff, allowing you to use these groups below. Note that you need to set a translation using a resource pack, otherwise an itemGroup.<id> translation key will appear. Do not use "none" as a name, as this is the key used to remove an item from any group.
	item_group = []
	#Removes item groups that have no items, including empty ones created by this mod. Runs after the below stuff, clearing up any empty groups left from moving all items out of them.
	remove_empty_item_groups = true
	#Whether to sort all item groups or not.
	sort = false
	#A list of groups that should be removed under all circumstances. Cannot remove "hotbar", "search" and "inventory".
	force_remove = []

#Dumps all corresponding values with their changeable properties into the logs. Dumping tilling transitions or villager trades is impossible code-wise, hence they are missing in this list.
[dump]
	#Dump blocks BEFORE applying the changes.
	dump_blocks = false
	#Dump blocks AFTER applying the changes.
	dump_blocks_after = false
	#Dump blocks BEFORE applying the changes. Only dumps non-default values. Does nothing if dump_blocks is set to true.
	dump_blocks_non_default = false
	#Dump blocks AFTER applying the changes. Only dumps non-default values. Does nothing if dump_blocks_after is set to true.
	dump_blocks_after_non_default = false
	#Dump items BEFORE applying the changes. Due to technical reasons, repair materials cannot be dumped.
	dump_items = false
	#Dump items AFTER applying the changes. Due to technical reasons, repair materials cannot be dumped.
	dump_items_after = false
	#Dump items BEFORE applying the changes. Repair materials cannot be dumped (technical limitations). Only dumps non-default values. Does nothing if dump_items is set to true.
	dump_items_non_default = false
	#Dump items AFTER applying the changes. Repair materials cannot be dumped (technical limitations). Only dumps non-default values. Does nothing if dump_items is set to true.
	dump_items_after_non_default = false
	#Dump enchantments BEFORE applying the changes.
	dump_enchantments = false
	#Dump enchantments AFTER applying the changes.
	dump_enchantments_after = false
	#Dump item groups BEFORE applying the changes.
	dump_groups = false
	#Dump item groups AFTER applying the changes.
	dump_groups_after = false
	#Dump composter inputs BEFORE applying the changes.
	dump_composter = false
	#Dump composter inputs AFTER applying the changes.
	dump_composter_after = false
	#Dump stripping transitions BEFORE applying the changes.
	dump_stripping = false
	#Dump stripping transitions AFTER applying the changes.
	dump_stripping_after = false
	#Dump pathing transitions BEFORE applying the changes.
	dump_pathing = false
	#Dump pathing transitions AFTER applying the changes.
	dump_pathing_after = false
	#The default enchantment value of items. Change this if you have a mod installed that makes every item enchantable. If you're unsure, leave this unchanged and run the item dumping. You'll see if you need to change it or not.
	#Range: > 0
	default_enchantment_value = 0

#Settings related to blocks. Format is "blockid;value", unless stated otherwise.
[blocks]
	#How long the block takes to break. 0.5 is dirt, 1.5 is stone, 50 is obsidian. -1 makes the block unbreakable. Not recommended for blocks with blockstate-dependent destroy time that may be added by other mods. Default value: 0
	destroy_time = []
	#How explosion-resistant the block is. 0.5 is dirt, 6 is stone and cobblestone, 1200 is obsidian. 3600000 or more makes the block completely explosion resistant. Default value: 0
	explosion_resistance = []
	#Whether you need a corresponding tool to get block drops (e.g. stone, ores) or if the harvest tool type only speeds up the breaking speed (e.g. dirt, gravel). Default value: false
	requires_tool = []
	#The light emitted by this block. Not recommended for blocks with blockstate-dependant light emission (e. g. furnaces). Default value: 0
	light_emission = []
	#The friction multiplier applied to entities moving on this block. Lower value means more slowdown. Default value: 0.6
	friction = []
	#Accelerates (if > 1) or slows down (if between 0 and 1) entities that walk upon this block. Default value: 1
	speed_factor = []
	#Allows entities on this block to jump higher (if > 1) or lower (if between 0 and 1). Default value: 1
	jump_factor = []
	#The sound type the block has. Only vanilla sound types are supported. Default value: stone. Vanilla sound types are:
	#wood, gravel, grass, lily_pad, stone, metal, glass, wool, sand, snow, ladder, anvil, slime_block, honey_block, wet_grass, coral_block, bamboo, bamboo_sapling, scaffolding, sweet_berry_bush, crop, hard_crop, vine, nether_wart, lantern, stem, nylium, fungus, roots, shroomlight, weeping_vine, twisting_vine, soul_sand, soul_soil, basalt, wart_block, netherrack, nether_bricks, nether_sprouts, nether_ore, bone_block, netherite_block, ancient_debris, lodestone, chain, nether_gold_ore, gilded_blackstone
	sound_type = []

#Settings related to items. Format is "item;value", unless stated otherwise.
[items]
	#The max durability an item has. Can only be set on damageable items. Default value: 0
	max_damage = ["quark:forgotten_hat;72", "longfallboots:longfallboots;512", "easypaxellite:wood_paxel;78", "easypaxellite:stone_paxel;172", "easypaxellite:iron_paxel;325", "easypaxellite:golden_paxel;42", "easypaxellite:diamond_paxel;2030", "easypaxellite:netherite_paxel;2640", "ae2:fluix_sword;350", "ae2:fluix_pickaxe;350", "ae2:fluix_shovel;350", "ae2:fluix_axe;350", "ae2:fluix_hoe;350", "additionaladditions:gilded_netherite_sword;2050", "additionaladditions:gilded_netherite_pickaxe;2050", "additionaladditions:gilded_netherite_shovel;2050", "additionaladditions:gilded_netherite_hoe;2050", "additionaladditions:gilded_netherite_axe;2050", "additionaladditions:gilded_netherite_helmet;472", "additionaladditions:gilded_netherite_chestplate;657", "additionaladditions:gilded_netherite_leggings;620", "additionaladditions:gilded_netherite_boots;546", "additionaladditions:rose_gold_sword;175", "additionaladditions:rose_gold_pickaxe;175", "additionaladditions:rose_gold_axe;175", "additionaladditions:rose_gold_shovel;175", "additionaladditions:rose_gold_hoe;175", "additionaladditions:rose_gold_helmet;177", "additionaladditions:rose_gold_chestplate;212", "additionaladditions:rose_gold_leggings;205", "additionaladditions:rose_gold_boots;191"]
	#The max stack size an item has. Can't be set on damageable items. Default value: 64 (1 for damageable items)
	max_stack_size = ["byg:white_puffball_stew;1"]
	#The item group (= creative tab) of an item. Use "none" to remove the item from any item group. Default value: none
	group = []
	#Whether the item should have the fire and lava shielding properties of netherite or not. Default value: false
	is_fire_resistant = []
	#Sets the item rarity (currently only affects text color). Must be one of common (white), uncommon (yellow), rare (aqua) and epic (light purple). Default value: common
	rarity = []
	#Sets the enchantment value of the item. Default value: the default enchantment value defined above
	enchantment_value = []
	#Sets the repair material of the item. Tags (e.g. #minecraft:planks) are also allowed.
	repair_material = []

	#Settings related to armor. Only armor items (excluding the elytra) can be affected, anything else will be skipped.
	[items.armor]
		#Sets the armor value.
		defense = ["additionaladditions:rose_gold_chestplate;5", "additionaladditions:rose_gold_leggings;3", "additionaladditions:rose_gold_boots;1"]
		#Sets the armor toughness value. Default value: 0
		toughness = ["additionaladditions:rose_gold_helmet;0", "additionaladditions:rose_gold_chestplate;1", "additionaladditions:rose_gold_leggings;1", "additionaladditions:rose_gold_boots;0"]
		#Sets the knockback resistance. Default value: 0
		knockback_resistance = []

	#Settings related to tools. Only tool, sword and trident items can be affected, anything else will be skipped.
	[items.tools]
		#Sets the attack damage.
		attack_damage = ["minecraft:wooden_axe;3.5", "minecraft:stone_axe;4.5", "minecraft:iron_axe;4.5", "minecraft:golden_axe;3.5", "minecraft:diamond_axe;4.5", "minecraft:netherite_axe;5", "additionaladditions:rose_gold_axe;3.25", "additionaladditions:gilded_netherite_axe;5", "ae2:certus_quartz_axe;4.5", "ae2:nether_quartz_axe;4.5", "ae2:fluix_axe;4.5", "botania:manasteel_axe;4.5", "botania:elementium_axe;4.5", "enigmaticlegacy:etherium_axe;8.0", "byg:pendorite_axe;5.5", "byg:pendorite_battleaxe;10", "byg:pendorite_sword;15", "twilightforest:ironwood_axe;4.5", "twilightforest:steeleaf_axe;5", "twilightforest:knightmetal_axe;5", "minecraft:netherite_sword;9", "additionaladditions:rose_gold_sword;4", "additionaladditions:gilded_netherite_sword;9", "easypaxellite:wood_paxel;3.5", "easypaxellite:stone_paxel;4", "easypaxellite:iron_paxel;4.5", "easypaxellite:golden_paxel;3.5", "easypaxellite:diamond_paxel;5", "easypaxellite:netherite_paxel;5.5", "ae2:fluix_sword;6.5", "ae2:fluix_pickaxe;4.5", "ae2:fluix_shovel;5", "ae2:fluix_hoe;1.5"]
		#Sets the attack speed.
		attack_speed = []
		#Sets the efficiency. Does not work for swords and tridents.
		efficiency = []

#Settings related to enchantments. Format is "enchantment;value", unless stated otherwise.
[enchantments]
	#The enchantment rarity of this enchantment. Must be one of common (10), uncommon (5), rare (2) and very_rare (1).
	rarity = []
	#The item group this enchantment type's enchanted books are in. As soon as you add one for an item group, you need to re-add every enchantment type for that group as well. Enchantment types are:
	#vanishable, breakable, wearable, armor, armor_chest, armor_feet, armor_head, armor_legs, weapon, digger, bow, crossbow, fishing_rod, trident
	group = []
	#Remove enchanted books from creative tabs. Runs before group, so re-adding is possible.
	remove_item_groups = false

[composter]
	#Define additional composter inputs. Format is "itemid;chance", with chance being a percentage between 0.0 and 1.0.
	inputs = []
	#Whether to clear the default composter inputs and have the composter inputs only contain the stuff defined here.
	clear = false

[stripping]
	#Define additional stripping transitions. Format is "fromid;toid", with both of them being in the modid:blockid format.
	transitions = []
	#Whether to clear the default stripping transitions and have the stripping transitions only contain the stuff defined here.
	clear = false

[pathing]
	#Define additional pathing transitions. Format is "fromid;toid", with both of them being in the modid:blockid format.
	transitions = []
	#Whether to clear the default pathing transitions and have the pathing transitions only contain the stuff defined here.
	clear = false

[tilling]
	#Define additional tilling transitions. Format is "fromid;toid", with both of them being in the modid:blockid format.
	transitions = []
	#Whether to clear the default tilling transitions and have the tilling transitions only contain the stuff defined here.
	clear = false

[entities]
	#Apply entity attribute modifiers on spawning. To get the default value of an attribute, make a superflat world without mob spawning, spawn the desired mob, and run "/attribute @e[type=<entityid>,limit=1] <attributeid> get". Format is "entity;attribute;amount;operation":
	#entity: the entity id (e.g. minecraft:rabbit)
	#attribute: the attribute id (e.g. minecraft:generic.max_health)
	#amount: the amount of the modifier (e.g. 5)
	#operation: 0 for addition, 1 for multiply base, 2 for multiply total. See https://minecraft.fandom.com/wiki/Attribute for more information
	modifiers = []

