
#General configurations. Shop contents stored in "adminshop.csv"
[server_config]
	#Amount of money each player starts with. Must be a whole number.
	#Range: 0 ~ 9223372036854775807
	starting_money = 0

