
#Client configurations. Options for changing display view
[display_config]
	#Displays your current balance and gained balance per second in the top left corner
	"Balance Display" = false
	#If monetary values should be formatted as M/B/T/etc (Short) instead of Million/Billion/Trillion/etc (Full)
	"Short mode " = true

