
#General settings
[general]
	#The CurseForge project ID for the modpack
	#Range: > 0
	modpackProjectID = 1286119
	#The name of the modpack
	modpackName = "Capitalia: Re-minted"
	#The version of the modpack
	modpackVersion = "Beta 0.1.1"
	#Use the metadata.json to determine the modpack version
	#ONLY ENABLE THIS IF YOU KNOW WHAT YOU ARE DOING
	useMetadata = false

