
[pipe]

	[pipe.item]

		[pipe.item.basic]
			#The maximum amount of ticks that items can be in the pipe. Lower is faster.
			#Range: > 0
			maxTicks = 100

		[pipe.item.improved]
			#The maximum amount of ticks that items can be in the pipe. Lower is faster.
			#Range: > 0
			maxTicks = 60

		[pipe.item.advanced]
			#The maximum amount of ticks that items can be in the pipe. Lower is faster.
			#Range: > 0
			maxTicks = 20

	[pipe.fluid]

		[pipe.fluid.basic]
			#The capacity in mB of the pipe.
			#Range: > 0
			capacity = 100
			#The transfer rate in mB/t of the pipe.
			#Range: > 0
			transferRate = 10

		[pipe.fluid.improved]
			#The capacity in mB of the pipe.
			#Range: > 0
			capacity = 250
			#The transfer rate in mB/t of the pipe.
			#Range: > 0
			transferRate = 25

		[pipe.fluid.advanced]
			#The capacity in mB of the pipe.
			#Range: > 0
			capacity = 500
			#The transfer rate in mB/t of the pipe.
			#Range: > 0
			transferRate = 50

		[pipe.fluid.elite]
			#The capacity in mB of the pipe.
			#Range: > 0
			capacity = 1000
			#The transfer rate in mB/t of the pipe.
			#Range: > 0
			transferRate = 100

		[pipe.fluid.ultimate]
			#The capacity in mB of the pipe.
			#Range: > 0
			capacity = 2000
			#The transfer rate in mB/t of the pipe.
			#Range: > 0
			transferRate = 200

	[pipe.energy]

		[pipe.energy.basic]
			#The capacity in FE of the pipe.
			#Range: > 0
			capacity = 500
			#The transfer rate in FE/t of the pipe.
			#Range: > 0
			transferRate = 50

		[pipe.energy.improved]
			#The capacity in FE of the pipe.
			#Range: > 0
			capacity = 1000
			#The transfer rate in FE/t of the pipe.
			#Range: > 0
			transferRate = 100

		[pipe.energy.advanced]
			#The capacity in FE of the pipe.
			#Range: > 0
			capacity = 1500
			#The transfer rate in FE/t of the pipe.
			#Range: > 0
			transferRate = 250

		[pipe.energy.elite]
			#The capacity in FE of the pipe.
			#Range: > 0
			capacity = 2000
			#The transfer rate in FE/t of the pipe.
			#Range: > 0
			transferRate = 325

		[pipe.energy.ultimate]
			#The capacity in FE of the pipe.
			#Range: > 0
			capacity = 4000
			#The transfer rate in FE/t of the pipe.
			#Range: > 0
			transferRate = 500

	[pipe.attachment]

		[pipe.attachment.extractor]

			[pipe.attachment.extractor.basic]
				#The interval between item extractions in ticks. Lower is faster.
				#Range: > 0
				itemTickInterval = 100
				
				#The amount of items to extract per extraction.
				#Range: 0 ~ 64
				itemsToExtract = 1
				
				#The interval between fluid extractions in ticks. Lower is faster.
				#Range: > 0
				fluidTickInterval = 100
				
				#The amount of fluids in mB to extract per extraction.
				#Range: > 0
				fluidsToExtract = 100
				
				#The amount of filter slots allowed.
				#Range: 0 ~ 15
				filterSlots = 0
				
				#Whether the redstone mode can be configured for this extractor.
				canSetRedstoneMode = false
				
				#Whether the extractor can be toggled between whitelist and blacklist.
				canSetWhitelistBlacklist = false
				
				#Whether the extractor can be toggled between routing modes.
				canSetRoutingMode = false
				
				#Whether the extractor can toggle exact mode.
				canSetExactMode = false

			[pipe.attachment.extractor.improved]
				#The interval between item extractions in ticks. Lower is faster.
				#Range: > 0
				itemTickInterval = 80
				
				#The amount of items to extract per extraction.
				#Range: 0 ~ 64
				itemsToExtract = 4
				
				#The interval between fluid extractions in ticks. Lower is faster.
				#Range: > 0
				fluidTickInterval = 100
				
				#The amount of fluids in mB to extract per extraction.
				#Range: > 0
				fluidsToExtract = 250
				
				#The amount of filter slots allowed.
				#Range: 0 ~ 15
				filterSlots = 3
				
				#Whether the redstone mode can be configured for this extractor.
				canSetRedstoneMode = true
				
				#Whether the extractor can be toggled between whitelist and blacklist.
				canSetWhitelistBlacklist = true
				
				#Whether the extractor can be toggled between routing modes.
				canSetRoutingMode = false
				
				#Whether the extractor can toggle exact mode.
				canSetExactMode = true

			[pipe.attachment.extractor.advanced]
				
				#The interval between item extractions in ticks. Lower is faster.
				#Range: > 0
				itemTickInterval = 60
				
				#The amount of items to extract per extraction.
				#Range: 0 ~ 64
				itemsToExtract = 16
				
				#The interval between fluid extractions in ticks. Lower is faster.
				#Range: > 0
				fluidTickInterval = 100
				
				#The amount of fluids in mB to extract per extraction.
				#Range: > 0
				fluidsToExtract = 500
				
				#The amount of filter slots allowed.
				#Range: 0 ~ 15
				filterSlots = 6
				
				#Whether the redstone mode can be configured for this extractor.
				canSetRedstoneMode = true
				
				#Whether the extractor can be toggled between whitelist and blacklist.
				canSetWhitelistBlacklist = true
				
				#Whether the extractor can be toggled between routing modes.
				canSetRoutingMode = true
				
				#Whether the extractor can toggle exact mode.
				canSetExactMode = true

			[pipe.attachment.extractor.elite]
				#The interval between item extractions in ticks. Lower is faster.
				#Range: > 0
				itemTickInterval = 40
				
				#The amount of items to extract per extraction.
				#Range: 0 ~ 64
				itemsToExtract = 32
				
				#The interval between fluid extractions in ticks. Lower is faster.
				#Range: > 0
				fluidTickInterval = 100
				
				#The amount of fluids in mB to extract per extraction.
				#Range: > 0
				fluidsToExtract = 1000
				
				#The amount of filter slots allowed.
				#Range: 0 ~ 15
				filterSlots = 9
				
				#Whether the redstone mode can be configured for this extractor.
				canSetRedstoneMode = true
				
				#Whether the extractor can be toggled between whitelist and blacklist.
				canSetWhitelistBlacklist = true
				
				#Whether the extractor can be toggled between routing modes.
				canSetRoutingMode = true
				
				#Whether the extractor can toggle exact mode.
				canSetExactMode = true

			[pipe.attachment.extractor.ultimate]
				#The interval between item extractions in ticks. Lower is faster.
				#Range: > 0
				itemTickInterval = 20
				
				#The amount of items to extract per extraction.
				#Range: 0 ~ 64
				itemsToExtract = 64
				
				#The interval between fluid extractions in ticks. Lower is faster.
				#Range: > 0
				fluidTickInterval = 100
				
				#The amount of fluids in mB to extract per extraction.
				#Range: > 0
				fluidsToExtract = 2000
				
				#The amount of filter slots allowed.
				#Range: 0 ~ 15
				filterSlots = 15
				
				#Whether the redstone mode can be configured for this extractor.
				canSetRedstoneMode = true
				
				#Whether the extractor can be toggled between whitelist and blacklist.
				canSetWhitelistBlacklist = true
				
				#Whether the extractor can be toggled between routing modes.
				canSetRoutingMode = true
				
				#Whether the extractor can toggle exact mode.
				canSetExactMode = true